"""empty message

Revision ID: 0e4649017bf9
Revises: 9425f063387e
Create Date: 2019-04-27 21:14:30.655751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e4649017bf9'
down_revision = '9425f063387e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sl_good_info', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sl_good_info', sa.Column('status', mysql.VARCHAR(length=32), server_default=sa.text("'False'"), nullable=True))
    # ### end Alembic commands ###
