"""empty message

Revision ID: 2c4fccefa089
Revises: 
Create Date: 2019-04-27 10:50:28.281561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c4fccefa089'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sl_user_profile',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('province', sa.String(length=32), nullable=False),
    sa.Column('city', sa.String(length=32), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=True),
    sa.Column('openid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sl_user_profile_openid'), 'sl_user_profile', ['openid'], unique=False)
    op.create_table('sl_dynamic_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=256), nullable=False),
    sa.Column('content_image_url', sa.String(length=128), nullable=True),
    sa.Column('good_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['sl_user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sl_comment_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dynamic_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=1024), nullable=True),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dynamic_id'], ['sl_dynamic_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sl_good_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dynamic_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dynamic_id'], ['sl_dynamic_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sl_replay_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('replay_type', sa.String(length=64), nullable=True),
    sa.Column('content', sa.String(length=1024), nullable=True),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['sl_comment_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sl_replay_info')
    op.drop_table('sl_good_info')
    op.drop_table('sl_comment_info')
    op.drop_table('sl_dynamic_info')
    op.drop_index(op.f('ix_sl_user_profile_openid'), table_name='sl_user_profile')
    op.drop_table('sl_user_profile')
    # ### end Alembic commands ###
