"""empty message

Revision ID: 76008cb6e33d
Revises: 7bd9ee31140d
Create Date: 2019-04-28 12:50:52.715287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76008cb6e33d'
down_revision = '7bd9ee31140d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sl_dynamic_info', 'good_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sl_dynamic_info', sa.Column('good_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
