"""empty message

Revision ID: 9425f063387e
Revises: fd06a7bde1bf
Create Date: 2019-04-27 20:14:42.751708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9425f063387e'
down_revision = 'fd06a7bde1bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sl_good_info', sa.Column('status', sa.String(length=32), server_default='False', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sl_good_info', 'status')
    # ### end Alembic commands ###
