"""empty message

Revision ID: cc3882fdf944
Revises: 2c4fccefa089
Create Date: 2019-04-27 14:49:43.625073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc3882fdf944'
down_revision = '2c4fccefa089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sl_good_info', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sl_good_info', 'user_id')
    # ### end Alembic commands ###
